### ISSUE TITLE
Подключение pdf js с настройками

### ISSUE THREAD

**Issue by witzawitz** [pulsarvp/le-pdf#1]
1. path - путь к pdf, единственный обязательный параметр
1. ~orientation: "landscape", default - portrait~ АВТОопределение исходя из размеров страницы.
1. width - не обязательный параметр. Если указан, то выставлять ширину страницы равной width, если не указан - то делать ширину страницы равной ширине контейнера. Высоту страницы всегд подгонять соответственно ширине.
1. direction - horizontal/vertical, default=vertical . Если выставлена вертикальная прокрутка, то она должна быть плавной, при нажатии ↑/↓  прокручивать на 1/2 высоты страницы. Если горизонтальная прокрутка, то при нажатии ←/→ прокручивать на одну страницу.

 Кнопки навигации (следующая/предыдущая страница) показывать всегда. Для горизонтальной прокрутки - это кнопки влево/вправо, для вертикальной - вверх/вниз.

**Comment by adinvadim** [comment]
констркутор lePdf будет иметь два параметра, первый - это `element` DOM элемент, внутри котогорого инцилизировать все. Второй это `options`.

**Comment by witzawitz** [comment]
1. Сделать активное состояние для кнопок, чтобы менялся цвет при клике и хавере.
1. Скрол горизонтальный не работает с тачпада.
1. Показывать лоадер пока пдф грузится.
1. Если не загрузилось - то текст ошибки "Ошибка загрузки файла."
1. Не видно разделителей страниц в вертикальной ориентации (полупрозрачный серый).
1. Запилить лоадер из логотипа Пульсара.
﻿https://www.dropbox.com/s/a6dsmgs0k9cpi87/pulsarvp-logo-ru.svg?dl=0
1. У панели с кнопками как-то обозначить нижнюю границу, чтобы эта панель не сливалась с документом.
